### ISSUE TITLE
Renders using metaData fail because it is undefined

### ISSUE THREAD

**Issue by nbgo** [yorl1n/ext.ExportableGrid#1]
Please look at this screenshot: https://s3.amazonaws.com/donnicky_screenshots/2016-03-03_22-22-56_d74ea5b5-42c4-4e61-b6b5-9bc0fb782db9.png

**Comment by yorl1n** [comment]
Thanks for report. I'll take a look

**Comment by yorl1n** [comment]
metadata is now provided for summaryRenderer
