### ISSUE TITLE
Render call context differs with ExtJS logic.

### ISSUE THREAD

**Issue by nbgo** [yorl1n/ext.ExportableGrid#2]
Please look at this screenshot: https://s3.amazonaws.com/donnicky_screenshots/2016-03-03_22-34-17_c93c2d41-2aa6-4b4f-b1c7-f10cea7d1ded.png
ExtJS logic calls render so that `this` references grid. In your code `this` references column.

**Comment by yorl1n** [comment]
Thanks for report. I'll take a look

**Comment by yorl1n** [comment]
Now the scope should be correct
