### ISSUE TITLE
error: view is undefined in generateWorksheets line 458 with lockable grids

### ISSUE THREAD

**Issue by abenhamdine** [yorl1n/ext.ExportableGrid#5]
Hi, and thx for this great module.

Unfortunately, I'm unable to do it work (extjs 6.0.1), I'm running into the following error : 
![image](https://cloud.githubusercontent.com/assets/7466144/20705850/ee5b56ba-b624-11e6-994a-d07925b3f71d.png)

The culprit is `view` in line 458, that is undefined : 
![image](https://cloud.githubusercontent.com/assets/7466144/20705963/5ccf3bde-b625-11e6-899a-fff1235819f0.png)
 
If I replace view by this.getView(), it doesn't work either because there's no property features.

The only properties 'features' I found out are : 
this.getView().normalGrid.features
this.getView().normalView.features
this.getView().lockedGrid.features
this.getView().lockedView.features

Could you provide me some help ? Or ideas ?

FWIW, I'm using a grid that extends another grid that extends ExportableGrid.

Thx in advance.

**Comment by abenhamdine** [comment]
If I add line 457 : 
```js
this.view = this.getView().normalGrid;
```
the export is working fine, but it seems like a crazy hack...

**Comment by yorl1n** [comment]
Hi, it looks like you are using a locking grid. And as per discussion [here](https://www.sencha.com/forum/showthread.php?304751-Exportable-in-xlsx-grid&p=1166691#post1166690) this plugin has problems with locking grids. Unfortunately I haven't had enough time to investigate the problem. Could you please test it without locking features?

**Comment by abenhamdine** [comment]
ah yes, enableLocking is true.
I will test without, and let you know.
According to this [discussion](https://www.sencha.com/forum/showthread.php?236988-How-to-get-handle-reference-to-grid-features-(so-can-set-grid-filters)&p=871182&viewfull=1#post871182), I understand that we can handle the api differences by testing enableLocking  and get the according view.

**Comment by yorl1n** [comment]
Just added support of locked grids, could you please test it. Thanks.

**Comment by abenhamdine** [comment]
It seems to work pretty well 👍  .
Thx a lot !!!💃
