### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Sogl** [yorl1n/ext.ExportableGrid#6]
Hello!

I can't find any info how to install your plugin into the existing ExtJS 6.x project. I use v. 6.2. 
Can you update a readme and provide small instruction, please?

p.s. Demo Fiddle doesn't work, I see "Loading fiddle..." all the time:
https://fiddle.sencha.com/#fiddle/t37

Same with:
https://fiddle.sencha.com/#fiddle/1jtu
that I found in Sencha forum.

**Comment by yorl1n** [comment]
Hi unfortunately it is a ExtJs team style to broke every functionality with new update. So the fiddle itself was updated and now is inaccessible. I'll try to update readme with example and fiddle today.

**Comment by yorl1n** [comment]
I have added explanation how to add UX component to the project and fixed the fiddle(not so complete as it was, but I will update it in future)
